### ISSUE TITLE
Using columns in both group_cols and TaQL returns empty dataset

### ISSUE THREAD

**Issue by JonahDW** [ska-sa/dask-ms#94]
* dask-ms version: 0.2.3
* Python version: 3.7.4
* Operating System: Ubuntu 16.04.6 LTS (Xenial Xerus)

I'm attempting to use xds_from_ms to select corrected data from a specific baseline in a dataset. Using the query structure:

```
mytaql = '(FIELD_ID==0) && (DATA_DESC_ID==0) && (ANTENNA1==2) && (ANTENNA2==5)'

corrected_data = daskms.xds_from_ms(myms, columns=['CORRECTED_DATA', 'TIME', 'FLAG', 'FIELD_ID', 'UVW'], taql_where=mytaql)
```
Returns an empty dataset, whereas the same query run in the table environment of CASA returns 300 rows. It's clear that the data is there, but somehow not picked up. If I drop the antenna requirements, the expected xarray dataset is returned.

Cheers

**Comment by JonahDW** [comment]
In fact, it seems any WHERE clause that does not select the full data returns nothing, which seems to defeat the entire purpose of it.

Any ideas what might be the issue here?

**Comment by sjperkins** [comment]
Hi @JonahDW. Thanks for reporting the issue and apologies for not getting back to you sooner.

By default `xds_from_ms` partitions the data by FIELD_ID and DATA_DESC_ID as mentioned in the [API](https://dask-ms.readthedocs.io/en/latest/api.html#daskms.xds_from_ms) Thus, if there are multiple fields and data descriptors, it will return multiple datasets in a list, which is further elaborated on in the [tutorial](https://dask-ms.readthedocs.io/en/latest/tutorial/reads.html#grouping).

I suspect the problem here is that mixing columns in `taql_where` and `group_cols` tends to create problems, because dask-ms itself internally constructs TAQL using `taql_where` to partition datasets by `group_cols`.

In dask-ms's `taql_where` [test cases](https://github.com/ska-sa/dask-ms/blob/45e9c1ad4490fb75b026a01cfe7bbaaa41c06152/daskms/tests/test_ms_read_and_update.py#L153-L190) for example, the following works:

```python

    # Group columns case
    xds = xds_from_table(ms, taql_where="FIELD_ID >= 0 AND FIELD_ID < 2",
                         group_cols=["DATA_DESC_ID", "SCAN_NUMBER"],
                         columns=["FIELD_ID"])
```

So this is a somewhat tricky bug to fix and I'll have to spend some time thinking about if it can be dealt with in a reasonable manner.

As a workaround I would set `group_cols=[]`:

```python
mytaql = '(FIELD_ID==0) && (DATA_DESC_ID==0) && (ANTENNA1==2) && (ANTENNA2==5)'

corrected_data = daskms.xds_from_ms(myms, group_cols=[], columns=['CORRECTED_DATA', 'TIME', 'FLAG', 'FIELD_ID', 'UVW'], taql_where=mytaql)
```

or remove FIELD_ID and DATA_DESC_ID from the taql and manually iterate though the grouped datasets.

```python
mytaql = '(ANTENNA1==2) && (ANTENNA2==5)'

corrected_data = daskms.xds_from_ms(myms, columns=['CORRECTED_DATA', 'TIME', 'FLAG', 'FIELD_ID', 'UVW'], taql_where=mytaql)

for ds in corrected_data:
   if ds.DATA_DESC_ID !=0 or ds.FIELD_ID != 0:
      continue
```

**Comment by JonahDW** [comment]
Hey @sjperkins, thanks for the response and for looking into it.

For anyone else running into this, I found that the `group_cols=[]` worked like a charm, so thanks for that!

Cheers
